DROP TABLE IF EXISTS studios CASCADE;
DROP TABLE IF EXISTS actors CASCADE;
DROP TABLE IF EXISTS reviewers CASCADE;
DROP TABLE IF EXISTS films CASCADE;

CREATE TABLE studios(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  city TEXT, 
  state TEXT, 
  country TEXT
);

CREATE TABLE actors(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  date_of_birth DATE,
  place_of_birth TEXT
);

CREATE TABLE reviewers(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  name TEXT NOT NULL,
  company TEXT NOT NULL
);

CREATE TABLE films(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  title TEXT NOT NULL,
  studio INTEGER NOT NULL,
  released INT NOT NULL CHECK (released <= 9999 AND released >= 1000),
  talent JSONB NOT NULL
);